name: Generate ascii Artwork

on:  
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: install cowsay program
      run: sudo apt-get install cowsay -y
    - name: execute cowasat
      run: |
        cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        ls
        cat dragon.txt
    - name: upload artifacts
      uses: actions/upload-artifacts@v4
      
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-slim
    steps:
    - name: sleep for 10 seconds
      run: sleep 10
    - name: download
      uses: actions/download-artifacts@v4
    - name: grep dragon file
      run: grep -i dragon dragon.txt
  deploy_job_3:
    needs: build_job_1
    runs-on: ubuntu-24.04-arm
    steps:
    - name: download
      uses: actions/download-artifacts@v4    
    - name: read that file
      run: cat dragon.txt
  
      
