name: Generate ascii Artwork

on:  
  push

jobs:
  ascii_job:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: executing  shell script
      run: cd .github/workflows; ls;chmod +x ascii-script.sh;   ./ascii-script.sh  
      
