name: my first workflow
on: 
  push:
    branches:
      - main
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: say hello
        run: |
          echo "Hello, Adi! isn't it easy"
          ls -ltra
          cat README.md

      - name: Generate ASCII ArtWoek
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        
