name: matric configuration 

on:
  push:
  workflow_dispatch:
  
jobs:
  deploy-on-ubuntu:
    runs-on: [ubuntu-latest,windows-latest]
    steps:
      - name : echo docker details
        run: docker info
      - name:  run images
        run: docker run hello-world


