name: matric configuration 

on:
  push:
  workflow_dispatch:
  
jobs:
  deploy-on-multiple-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 1
    steps:
      - name: echo docker details
        run: docker info
      - name: run images
        run: docker run hello-world


