name: Workflow filters
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/59 * * * *'
  push:
    branches:
      - dev/* 
       # branches-ignore:
    #   - main/*
    # paths-ignore:
    #   - 'README.md'
    #   - 'docs/**'
    #   - 'scripts/**'
    #   - '.github/**'
  pull_request:
    types: [opened, closed]
    paths-ignore:
      - 'README.md'
    branches:
      - dev/*


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "this is executed with event type ${{github.event_name}}"
        
        
